### ISSUE TITLE
Bug using the calendar on the last lines

### ISSUE THREAD

**Issue by stdob** [revolist/revogrid#225]
When scrolling the grid to the end and opening the calendar, user interface bugs appear.

This bug happens in the latest versions of Chrome and Safari.

**To Reproduce**

* Open demo page https://revolist.github.io/revogrid/demo/ and scroll down:
![Screenshot 2021-07-01 at 14 52 22](https://user-images.githubusercontent.com/15095605/124128247-dfc59580-da7c-11eb-8703-a271f2fea688.jpg)

* Press the calendar button on the last line:
![Screenshot 2021-07-01 at 14 52 37](https://user-images.githubusercontent.com/15095605/124128578-3632d400-da7d-11eb-9ef5-dc0754c2f533.jpg)

* Close the calendar and scroll up a bit:
![Screenshot 2021-07-01 at 14 52 52](https://user-images.githubusercontent.com/15095605/124129013-a4779680-da7d-11eb-90f9-698e80e11951.jpg)

**Comment by revolist** [comment]
Hello @stdob 
Got this problem

Happening because the calendar is bound inside of the grid for scrolling compatibility together with the grid. Solution will be to take out the calendar to the external dom, better around body level, and use it from there. We shall work on this problem but can't promise a quick solution for now.

**Comment by revolist** [comment]
Fixed in v4
