### ISSUE TITLE
A problem when using VGridVueTemplate

### ISSUE THREAD

**Issue by JavaZWT** [revolist/revogrid#305]
Hello, @revolist ,first thank you for providing such a useful tool.

I've been using revogrid with vue in my project, and now I'm having some problems when using VGridVueTemplate.

When there are many VGridVueTemplate on columns,rendering will have problems.

https://codesandbox.io/s/revogrid-vuecomponent-forked-zehu41?file=/src/App.vue:1226-1242

Is there any way to avoid it?

thanks

**Comment by m2a2x** [comment]
Hello @JavaZWT, problem why it is slowing down your system is because of it adds new DOM element in order to support vue. Vue template was provided as a response for some users but our recommended way is to keep using internal way of handling template or tsx/jsx syntax which is just sugar for the first one https://revolist.github.io/revogrid/guide/jsx.template.html
