### ISSUE TITLE
Copy paste should create new rows and columns

### ISSUE THREAD

**Issue by agentaswin** [revolist/revogrid#338]
Hi,

Following is my requirement, if i copy rows from excel and paste it inside the table it should create new rows and copy the contents. With current framework i am not able to do so(upto my knowledge). Is there any hack or someway i can override this copy and paste behaviour?

Thanks upfront

**Comment by revolist** [comment]
You can build a plugin which would add more data to data source when you see something more than you have already inserted. Also it should be part of our Pro examples in v4.

**Comment by richardliebmann** [comment]
Would you be interessted in an open source solution as pull request or would you only provide this as a pro feature?

**Comment by revolist** [comment]
Hello @richardliebmann 

If you want to create it and make this part of the core we gladly accept it, we didn't work on it in pro hence we were focusing on much more complex features which require advance grid transformations such as row transpose, subtables, formulas etc.

**Comment by Techn1x** [comment]
I came here looking for this feature, after trying a bunch of events from the API docs and realising that none of the events occur before the range paste (so couldn't just expand the grid on paste)

Thanks for implementing it ! I wonder if it could be extendable to also adding columns

Looking at the PR, it uses `beforepasteapply` - since it's not in the API docs (as far as I can tell), is this a private / internal event? Or could I use it in my code as well?

**Comment by Techn1x** [comment]
For the time being until/if the plugin is merged, I managed write up an event handler for it

The main difficulty was there's no easy way I could see to get the "y" value of the paste - the plugin does this with providers, but from an event handler there's not much we can do. `grid.getSelectedRange()` returns a promise which isn't useful here. I managed to get it from `event.detail.event.target.dataset.rgrow` which might be bad

```ts
const beforePasteApply = (event: RevoGridCustomEvent<{ raw: string; parsed: string[][]; event: ClipboardEvent }>) => {
  if (!(event.detail.event.target instanceof HTMLElement) || !event.detail.event.target.dataset.rgrow) return

  const rowIndexOfPaste = Number.parseInt(event.detail.event.target.dataset.rgrow, 10)
  if (Number.isNaN(rowIndexOfPaste)) return

  const rowsToAdd = event.detail.parsed.length - (grid.source.length - rowIndexOfPaste)
  if (rowsToAdd > 0) {
    grid.source = [
      ...grid.source,
      ...Array.from({ length: rowsToAdd }, () => ({})),
    ]
  }
}
```

**Comment by nadilas** [comment]
Sorry to bother @richardliebmann, I'm new to revogrid, how on earth do you instantiate the AutoAddRowsOnPaste plugin? The [getPluginData](https://github.com/revolist/revogrid/blob/08334a701e299c499ff223f343c5297d7885f753/src/components/revoGrid/revo-grid.tsx#L1393) method is private but it's needed for the plugin constructor?

**Comment by richardliebmann** [comment]
Hi @nadilas,

you have to provide it as plugin in the revo-grid instance. 

Angular example:

```ts
export class SomeComponent {
    ....
    plugins = [
        AutoAddRowsPlugin
    ]
    ....
}
```

```html
<revo-grid theme="darkMaterial" [columns]="columns" [source]="items" [plugins]="plugins" ...></revo-grid>
```

**Comment by nadilas** [comment]
Thanks @richardliebmann, I tried that intuitively, and got the error:
MyComponent.vue:11  TypeError: Right-hand side of 'instanceof' is not an object
    at eval (plugin.service.ts:62:1)
    at Array.find (overrides.js:10:21)
    at eval (plugin.service.ts:62:1)
    at Array.forEach (<anonymous>)
    at PluginService.addUserPluginsAndCreate (plugin.service.ts:60:1)
    
    
```ts
// Step 3: Register user plugins
    plugins?.forEach(userPlugin => {
      // check if plugin already exists, if so, skip
      const existingPlugin = this.internalPlugins.find(
        createdPlugin => createdPlugin instanceof userPlugin, // <<<<
      );
      if (existingPlugin) {
        return;
      }
      this.add(new userPlugin(element, pluginData));
    });
```

**Comment by revolist** [comment]
We'll need to look into it. Now we have a better way to handle plugins with new plugin provider

**Comment by revolist** [comment]
Closing this as implemented for row growth on paste.

RevoGrid now exposes `AutoAddRowsPlugin` from the package root. When registered through the grid `plugins` property, it listens before paste is applied, adds any missing main rows, and emits a cancelable `newRows` event so applications can provide defaults or block insertion.

Usage is documented in the clipboard guide with:

```ts
import { AutoAddRowsPlugin } from '@revolist/revogrid';

grid.plugins = [AutoAddRowsPlugin];
```

I also added e2e coverage for registering the plugin, pasting past the last row, customizing generated row data through `newRows`, and canceling row creation.

One important scope note: the plugin intentionally adds rows only. RevoGrid does not automatically create columns during paste, because columns require application-owned definitions such as `prop`, header text, sizing, renderers, editors, and validation rules. For wider pasted data, applications should update `grid.columns` themselves before paste is applied or handle `beforepasteapply`.
