### ISSUE TITLE
Dynamically fix columns to start/end

### ISSUE THREAD

**Issue by Shubham20015** [revolist/revogrid#343]
Anyone had any idea how to dynamically (means on the basis of user input) fix the particular columns in revogrid in vue3 using composition API. If anyone have any codesandbox link how to implement this if it is possible, please share with me.
I know how to do in code using pin: 'colPinStart' but on re-render the component on basis of user input of how many columns he/she wants to fix at start/end, it does not effect on columns.

**Comment by Karan9615-off** [comment]
@m2a2x 

**Issue: Re-rendering Columns with Checkbox Inputs in Selectable Rows Table
Description:**

We've implemented a selectable rows table using checkbox inputs within the cellTemplate. The table allows users to select rows via checkboxes, and there's functionality to remove selected rows. However, we're encountering an issue where the checkbox inputs are not updating correctly when rows are removed. Specifically, the checkboxes in the remaining rows do not reflect the updated state after rows have been deleted.

**Problem:**

The checkbox inputs are passed in the cellTemplate of the table.
When rows are removed, the checkbox states are not re-rendered or updated accordingly.
We need a way to ensure that the checkbox cells are refreshed whenever rows are modified.
Question:

How can we re-render or refresh the columns to ensure that the checkbox cells are correctly updated after modifying the rows?

**Steps to Reproduce:**

Implement a table with selectable rows using checkboxes in the cellTemplate.
Add functionality to delete selected rows.
Observe that after deleting rows, the checkboxes in the remaining rows do not update as expected.
Expected Behavior:

Checkbox inputs should re-render and accurately reflect the selection state after any modifications to the rows.

**Current Workaround Attempts:**

We’ve tried manually forcing an update or using slots, but we’re still facing issues with the checkboxes not updating correctly.

**Comment by revolist** [comment]
hi @Karan9615-off it's not easy to understand your scenario based on description. Could you provide sandbox to check your problem?
