### ISSUE TITLE
vue3 VGrid component doesn't respect height style/css

### ISSUE THREAD

**Issue by disarticulate** [revolist/revogrid#461]
**Check if issue exists**
Nothing specific about auto height
**Describe the issue**
Docs say it should automagically figure out the height and width from css. I assume that also means style. I tried css, and it works if it's larger than the content grouping, but not smaller.

**To Reproduce**
Setup a grid and use grouping (optional)
```
      <VGrid
        style="height: 240px; width: 20ch"
        :columns="tableSchema"
        :source="tableSource"
        :columnTypes="tableColumnTypes"
        :grouping="tableGrouping"
      />
```

**Comment by revolist** [comment]
Hello, @disarticulate,

Thank you very much for your interest in the grid.

Regarding the auto height and width feature, you might have noticed that the <revo-grid/> has a min-height: 300px; applied by default. This was done intentionally because many users reported that the grid was not visible when no height was provided, resulting in a grid height of 0 if there is no containing element with a set height. The initial min-height: 300px; ensures that the grid is always visible. However, you can override this default by setting the height to 0 or any other value using CSS to fit your specific needs.

For future reference, we strongly recommend following our issue template and providing detailed examples. This helps us respond more effectively and assist you better. In cases like yours, providing an example on CodeSandbox along with some screenshots would be very helpful.

I am closing this issue as it does not present a new problem with the grid’s functionality. You can check a working example here: [CodeSandbox Example](https://codesandbox.io/p/sandbox/rg-461-grouping-vue-3-composition-api-66mx7t?file=%2Fsrc%2FApp.vue%3A3%2C34-3%2C35).

Best regards,
Revolist

**Comment by disarticulate** [comment]
thanks for the expediant reply. I understand that it can't figure out initial sizes and you'd prefer additional demo to troubleshoot.

I recommend you update the following docs to clarify with a demo what you suggest and claim the framework can do: https://revolist.github.io/revogrid/guide/grid.size.html

**Comment by revolist** [comment]
@disarticulate ty for the update
You are using incorrect/outdated document reference. Could you please explain how did you get it?

**Comment by disarticulate** [comment]
Google search.
